package com.didi.game.dao;

import com.didi.game.domain.ParkStruct;
import com.didi.game.domain.ParkStructExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ParkStructMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parkstruct
     *
     * @mbggenerated Thu Jul 19 20:31:05 CST 2018
     */
    int countByExample(ParkStructExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parkstruct
     *
     * @mbggenerated Thu Jul 19 20:31:05 CST 2018
     */
    int deleteByExample(ParkStructExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parkstruct
     *
     * @mbggenerated Thu Jul 19 20:31:05 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parkstruct
     *
     * @mbggenerated Thu Jul 19 20:31:05 CST 2018
     */
    int insert(ParkStruct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parkstruct
     *
     * @mbggenerated Thu Jul 19 20:31:05 CST 2018
     */
    int insertSelective(ParkStruct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parkstruct
     *
     * @mbggenerated Thu Jul 19 20:31:05 CST 2018
     */
    List<ParkStruct> selectByExample(ParkStructExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parkstruct
     *
     * @mbggenerated Thu Jul 19 20:31:05 CST 2018
     */
    ParkStruct selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parkstruct
     *
     * @mbggenerated Thu Jul 19 20:31:05 CST 2018
     */
    int updateByExampleSelective(@Param("record") ParkStruct record, @Param("example") ParkStructExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parkstruct
     *
     * @mbggenerated Thu Jul 19 20:31:05 CST 2018
     */
    int updateByExample(@Param("record") ParkStruct record, @Param("example") ParkStructExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parkstruct
     *
     * @mbggenerated Thu Jul 19 20:31:05 CST 2018
     */
    int updateByPrimaryKeySelective(ParkStruct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parkstruct
     *
     * @mbggenerated Thu Jul 19 20:31:05 CST 2018
     */
    int updateByPrimaryKey(ParkStruct record);
}